### ISSUE TITLE
Your LetsEncrypt cert expired on your site! 

### ISSUE THREAD

**Issue by MostHated** [mikaelm1/Blog-App-Buffalo#10]
Hey there,  
    I just wanted to let you know your cert on your site expired, so now it doesn't want to let me get to part 2 of the tutorial, lol. I had the page opened already from the other day and just sat back down to continue, when I reloaded the page it have me the error. : (

Thanks,
-MH

**Comment by MostHated** [comment]
I was able to just use Chrome to get to the site instead of Firefox to finish the tutorial, so all is well for that at least.

**Comment by mikaelm1** [comment]
@MostHated  I renewed the certificate just now, should be working properly now. Thank you for letting me know!

**Comment by MostHated** [comment]
Yup, working just fine now. Thanks for the tutorial, definitely appreciate it. :+1:
