### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by Dolbager** [mikaelm1/Blog-App-Buffalo#5]
When i try to run 
```buffalo setup``` 
i'am get error with 
```package github.com/mikaelm1/blog_app/actions: exit status 1```

**Comment by Pena86** [comment]
You are supposed to replace `mikaelm1` in the filepath with your own path.

Also in the tutorial, no imports are mentioned, they just throw an error when running the code. Some includes in this example repo don't exist anymore, example in the `actions/users.go`:
```
	"github.com/markbates/pop"
	"github.com/markbates/validate"
```
are now found in:
```
	"github.com/gobuffalo/pop"
	"github.com/gobuffalo/validate"
```

**Comment by mikaelm1** [comment]
I hadn't thought to include this when I wrote the setup instructions on the README, which I have now removed. @Pena86 is correct - thank you. Best to just follow the tutorial and build the project as readers go along. Unless someone wants to make a PR to update the README with a thorough set of instructions.
